### ISSUE TITLE
transitionInterval not working, showPageIndicators not working

### ISSUE THREAD

**Issue by shbatm** [shbatm/MMM-Carousel#1]
Opened on behalf of @MichiMich:

Hi there,

i tried out your module and installed it as mentioned. If i use your "Example - Slides Carousel" (copy-paste) it displays only the first slide and never gets to the next one. I tried also to enable the "showPageIndicators" but nothing happened. Do you think its possible to check this example and the functions? Or do i miss to install some other modules not mentioned in your ReadMe file?

Thanks and regards

Michael

**Comment by shbatm** [comment]
@MichiMich:

The "Example - Slides Carousel" config is from @barnabycolby's original repo; I have not checked to see if I broke it in my fork, but I will check the next chance I get (should be within the next week).

**Comment by MichiMich** [comment]
Thanks a lot. Did not check this... Now it works like a charm with transitionInterval: 0

**Comment by fatcatcgo** [comment]
It appears I can get the auto advance on every mode except slides.   Any ideas?  Original carousel advances.

**Comment by shbatm** [comment]
Please pull the latest update check if that fixed the problem.

```shell
cd ~/MagicMirror/modules/MMM-Carousel
git pull
```

**Comment by fatcatcgo** [comment]
Works perfectly.  Great work!
