### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by sharma-ji** [shbatm/MMM-Carousel#2]
The background of the page indicator is black, and I'm using a background image for my magicmirror, so its looks odd, how to make it transparent ?
![capture](https://user-images.githubusercontent.com/17575809/31058536-04d04e02-a713-11e7-9f71-491b88954c68.PNG)

**Comment by sharma-ji** [comment]
I found a bug as well, if you put 
` showPageIndicators: true,
            showPageControls: true,`
the modules fails its operation.

**Comment by E3V3A** [comment]
@shbatm 
Any updates?

**Comment by shbatm** [comment]
@E3V3A -- IIRC there was not actually a bug. This was a config problem on the users part. It was resolved on the MM2 forum (https://forum.magicmirror.builders/topic/5013/problem-with-alert-module/3).

**Comment by CarlosLabrado** [comment]
I know this is closed, but it was never answered. 
You can go to the MMM-Carousel.css then in the ".MMMCarouselContainer" section change the background color to:
`  background-color: rgba(0, 0, 0, 0);
`
