### ISSUE TITLE
[FEATURE REQUEST] Display the title of the page

### ISSUE THREAD

**Issue by Robiv8** [shbatm/MMM-Carousel#20]
Is there a way to display the title of the page?
As in MMM Page Selector
That would be cool

**Comment by shbatm** [comment]
Added. Please try it in the `develop` branch by adding `showPageTitles: 'top'` or `showPageTitles: 'bottom'` in your config.

#### To Checkout [Develop](https://github.com/shbatm/MMM-Carousel/tree/develop) Branch:
```shell
cd ~/MagicMirror/modules/MMM-Carousel
git fetch --all && git checkout develop
# Restart your MagicMirror
```

**Comment by Robiv8** [comment]
You are to fast for me 🥇 
Many thanks, I will try.
