### ISSUE TITLE
[FEATURE REQUEST] CSS for the title

### ISSUE THREAD

**Issue by Robiv8** [shbatm/MMM-Carousel#22]
Since I wanted the title without underline, I changed the MMM-Carousel.js.
Maybe that's of interest to you.

this line:
`hdr.classList.add ('module-header');`
in
`hdr.classList.add ('carousel-title');`

so I can control the title itself in the custome.css

```
.carousel-title {
    border: 0px;
}
```

**Comment by shbatm** [comment]
You should be able to customize without changing the file using:

```css
#MMMCarouselPageTitle {
  border: 0px;
}
```
