### ISSUE TITLE
[Bug] Positional Mode does not work on this branch

### ISSUE THREAD

**Issue by mlcampbe** [shbatm/MMM-Carousel#23]
**Describe the bug**
This module does not work for me. I install it and it appears to never load. The never has any rotated modules. However, if I remove this and install the barnabycolby/MMM-Carousel that one works just fine with the same configuration. Very odd, any ideas why?

**Configuration**
    {
      module: "MMM-Carousel",
      config: {
        transitionInterval: 10000,
        ignoreModules: ["clock"],
        mode: "positional",
        bottom_right: {enabled: true, ignoreModules: [], overrideTransitionInterval: 15000}
     }
   }

**Comment by shbatm** [comment]
I'm not sure. 99% of the changes I've made have been associated with the "slides" mode, but I very well could have broken something in the process.  If you are just using the positional rotations, you may be better off sticking with barnabycolby's version until I have an opportunity to test.

Is there a specific feature from my fork you were trying to get working (navigation buttons, etc)?

**Comment by mlcampbe** [comment]
No not really any specific reason to use your module other than the fact that it had a few more features. I don't plan on using those features now so I am ok with the barnabycolby version at this time.

**Comment by Eldeiss** [comment]
Hi,
Same problem her, regardless the configuration, barnabycolby's module is working but I cannot manage to run your's.
Maybe a problem from Electron that I have rebuild for MMM-AssistantMk2 ?

**Comment by drdada** [comment]
Hi, Same here, but even the barnabycolby version meets the issue.

Btw, thanks for always being active on this project.

**Comment by P8ntBal1551** [comment]
I'm having this issue as well. I'm pretty sure the barnabycolby version has the same issue as well.

here is my config
```
module: "MMM-Carousel",
position: "bottom_center",
config: {
        transitionInterval: 20000,
        ignoreModules: ["clock", "updatenotification", "alert"],
        mode: "positional",
        bottom_center: {enabled: true}
}
```

**Comment by KristjanESPERANTO** [comment]
@mlcampbe I added a position to your config, than it works for me:

```js
  {
    module: "MMM-Carousel",
    position: "bottom_center",
    config: {
      transitionInterval: 10000,
      ignoreModules: ["clock"],
      mode: "positional",
      bottom_right: {enabled: true, ignoreModules: [], overrideTransitionInterval: 15000}
    }
  },
```
That doesn't match the documentation. I'm not that into the code so I'm not sure if we should update the documentation or this is a buggy behavior.

**Comment by P8ntBal1551** [comment]
@KristjanESPERANTO 

Thank you. Sorry. Didn't know that "ignoreModules: []" was required

**Comment by KristjanESPERANTO** [comment]
I'm closing this issue. The missing position can be dealt in issue #37.
