### ISSUE TITLE
MMM-Carousel is not loaded

### ISSUE THREAD

**Issue by raoel** [shbatm/MMM-Carousel#25]
It does not seem to matter much what I set for configuration (I tried both modes 'global' and 'slides'), it looks like MMM-Carousel will not start.
I do not get page indicators, there is no carousel, nothing has changed since I added this module.

Could it be an issue with MM version 2.10.0?

From what I can see in main.js line 120 (which is part of MM-core) 'newContent' is 'undefined' here:
```
		newContentPromise.then(function(newContent) {
				var updatePromise = updateDomWithContent(module, speed, newHeader, newContent);

				updatePromise.then(resolve).catch(Log.error);
			}).catch(Log.error);
```

newContentPromise is filled with `var newContentPromise = module.getDom();`

my configuration:

```
  {
            module: 'MMM-Carousel',
            position: 'bottom_bar',
            config: {
                mode: 'global',
                ignoreModules: ['alert', 'clock', 'currentweather'],
                showPageIndicators: true,
                showPageControls: true,
                transitionInterval: 5000,
            }
        },
```

If you need anything more, please let me know :-)

I'm working with a very small screen, so your module would be a great help!

**Comment by raoel** [comment]
ah, I did some digging:

with other that 'slides' the 'MODULE_DOM_CREATED' is never received (probably due to the fact that getDom() returns undefined for anything else than 'slides'.

I do not want slides, but I'm trying to make it work with them.

Unfortunately, the 'previous' and 'next' buttons are invisible. I don't know why, but when I hover my mouse I can see them, but this is not a great solution because I want to use my touchscreen, and not my mouse :-)

**Comment by raoel** [comment]
ah, there's opacity on the buttons which makes them invisible

still, they only work with mouse.. I can't really figure out what happens when they are clicked, so I don't know what to do about that.

**Comment by fordsteve** [comment]
I have got this working. I originally installed Carousel via MM Package Manager and the module folder wasn't spelt correctly, i had to rename to MMM-Carousel and then BOOM!!! working. Well chuffed. Only in my first week on PI too!
