### ISSUE TITLE
[FEATURE REQUEST] Way to use this with a touchscreen?

### ISSUE THREAD

**Issue by StarrKiss** [shbatm/MMM-Carousel#26]
So, I am running Magic Mirror2 on a raspberry pi with a 7 inch touchscreen. As far as I can see, there is no way to swap pages in slide mode with the touchscreen. Is there any way to do this?

**Comment by chrisparker787** [comment]
I would like this as well!

**Comment by shbatm** [comment]
Make sure you have `showPageControls: true` in the module config and then you should have two "hidden" arrow buttons on the lower left/right corners to navigate. If using a mouse these will appear when you hover over them (you can force them to always show if you add some custom css to your `custom.css` file).

**Comment by MarvellousMili** [comment]
Can I just slide the page like on the phones?

**Comment by lhoggatt** [comment]
> Make sure you have `showPageControls: true` in the module config and then you should have two "hidden" arrow buttons on the lower left/right corners to navigate. If using a mouse these will appear when you hover over them (you can force them to always show if you add some custom css to your `custom.css` file).

What would that custom CSS be? I'd like the buttons to show all the time on my touchscreen.

**Comment by shbatm** [comment]
> What would that custom CSS be? I'd like the buttons to show all the time on my touchscreen.

.control label {
  opacity: 0.5;
}
