### ISSUE TITLE
Mute Individual Carousel Windows

### ISSUE THREAD

**Issue by ghost** [shbatm/MMM-Carousel#28]
This feature would fix alot of the way other people build video apps, i have tested a bunch and not one of them can mute properly at all, so this would fix all the other modules out there so i could run google assistant with multiple pages that are displaying other feeds from things, or have multiple windows with different feeds that i can mute specifically when i want to listen to each thing, this would be a great modification to increase versatility and more windows

**Comment by shbatm** [comment]
This module already calls the hide method of the other modules. If they support playing audio, then they should mute when that method is called.
