### ISSUE TITLE
Advanced Slide example is wrong

### ISSUE THREAD

**Issue by werriq** [shbatm/MMM-Carousel#3]
Hi,
I think the example for advanced slides is wrong.  The carouselId should be set with ": " and not " = ".
Not working:
`{name:'clock', classes:'zoom200', position:"middle_center", carouselId = "1"}`

Working:
`{name:'clock', classes:'zoom200', position:"middle_center", carouselId: "1"}`

**Comment by shbatm** [comment]
Good Catch, Thanks! This has been corrected.
