### ISSUE TITLE
[FEATURE REQUEST] Add support for rotationHomePage

### ISSUE THREAD

**Issue by nitewing76** [shbatm/MMM-Carousel#30]
Requesting a feature that when the screen is idle for a set amount of time _n_, the carousel returns to the main/home page.

This will allow users to walk away, then if they return after _n_ seconds, the screen will be on the home page.

[MMM-Pages](https://github.com/edward-shen/MMM-pages) refers to this as "rotationHomePage". In my limited experience (MM day 3), MMM-Carousel seems to operate smoother and does not require another module for the page indicators.

**Comment by shbatm** [comment]
Closed with 22b64b2
