### ISSUE TITLE
[Bug] Navigation Page Controls and Indicators Not Working

### ISSUE THREAD

**Issue by gddhub** [shbatm/MMM-Carousel#92]
**Describe the `bug**`

I have set up MMM-Carousel in slide mode and it was working just fine until last night and I'm not sure what I did to break it. Currrently it transitions from slide to slide on time but when it gets to slide 3, the Page Indicator does not show the third circle as filled. The second circle remains filled as though it were still on page 2, even though the modules displayed correspond with slide 3.

In addition the navigation arrows when on slide three do not work to change slides correctly. The back/left arrow goes back to slide 1, bypassing slide 2. The forward/right arrow which used to go back to slide 1, does nothing.

```
{
			module: "MMM-Carousel",
			position: "bottom_bar", // Required only for navigation controls
			config: {
				transitionInterval: 20000,
				ignoreModules: ["alert"],
				mode: "slides",
				showPageIndicators: true,
				showPageControls: true,
				slides: {
					"1": [
					{name:"clock",position:"top_left",carouselId: "clock1"},
					{name:"MMM-CalendarExt3Agenda",position:"top_left"},					
					"compliments", 
					"weather",
					"MMM-WeatherAlerts",
					"MMM-WordOfTheDay",
					"MMM-MyScoreboard",
					"MMM-MicrosoftToDo"
					],
					
					"2": [
					"MMM-CalendarExt3",
					{name:"clock",classes:'zoom50',position:"top_left",carouselId: "clock2"}
					],
					
					"3": [
					{name:"MMM-OpenWeatherMapForecast",position:"upper_third",carouselId: "Current"},
					{name:"clock",classes:'zoom50',position:"top_left",carouselId: "clock2"},
					"MMM-DynamicWeather"
					],
					
					"4": [
					{name:"clock",classes:'zoom50',position:"top_left",carouselId: "clock2"},
					"MMM-WeatherChart"
					]
				}
			}
		},

```
Any thoughts on what is happening here?

**Comment by KristjanESPERANTO** [comment]
To figure it out, try a simpler configuration with only one module in one slide. Like this:

```js
				slides: {
					"1": [{ name: "calendar" }],
					"2": [{ name: "newsfeed" }],
					"3": [{ name: "compliments"}]
				}
```

Do you have the same issue with a simple config like that?

**Comment by KristjanESPERANTO** [comment]
As there was no response I am closing this issue. Feel free to open it again if the problem still exists.
